# SageMath para físicos
***
Rogério T. C.

## Aula III

## 1. Vetores e matrizes

In [1]:
%display latex
reset()

#### Vetores e estrutura

Vetores são constrídos pelo comando `vector`, com sintaxe `vector([x1,x2,x3,...,xn])`

In [2]:
v = vector([x,x^8,5])

In [3]:
print(parent(v))

Vector space of dimension 3 over Symbolic Ring


#### Soma, multiplicação escalar e produto vetorial

In [4]:
w=vector([5,2,1])

In [5]:
v.cross_product(w)

(x^8 - 10, -x + 25, -5*x^8 + 2*x)

#### Produto interno

In [6]:
v*w

2*x^8 + 5*x + 5

In [7]:
v.dot_product(w)

2*x^8 + 5*x + 5

#### Hermitiano

In [8]:
var('y', domain='real')

y

In [9]:
z = vector([I*2,x,y]);

In [10]:
z*w

2*x + y + 10*I

In [11]:
z.hermitian_inner_product(w)

y + 2*conjugate(x) - 10*I

#### Norma

In [12]:
w.norm()

sqrt(30)

In [13]:
z.norm()

sqrt(y^2 + abs(x)^2 + 4)

#### Matrizes

In [14]:
a = matrix(SR,[[1,2,3],[5,23,8],[8,5,1]]);a

[ 1  2  3]
[ 5 23  8]
[ 8  5  1]

In [15]:
(a).transpose()*z

(5*x + 8*y + 2*I, 23*x + 5*y + 4*I, 8*x + y + 6*I)

In [16]:
z*a

(5*x + 8*y + 2*I, 23*x + 5*y + 4*I, 8*x + y + 6*I)

#### Matrizes especiais

In [17]:
matrix.zero(10,15)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

In [18]:
matrix.identity(4)

[1 0 0 0]
[0 1 0 0]
[0 0 1 0]
[0 0 0 1]

In [19]:
matrix.ones(3)

[1 1 1]
[1 1 1]
[1 1 1]

In [20]:
d = matrix.diagonal([y,y,y^2])

#### Determinante, traço, transposta, inversa, conjugada

In [21]:
d.det()

y^4

In [22]:
d.trace()

y^2 + 2*y

In [23]:
d.transpose()

[  y   0   0]
[  0   y   0]
[  0   0 y^2]

In [24]:
d.conjugate()

[  y   0   0]
[  0   y   0]
[  0   0 y^2]

In [25]:
d.inverse()

[   1/y      0      0]
[     0    1/y      0]
[     0      0 y^(-2)]

#### Pausa - transformação linear

In [26]:
T = linear_transformation(a)

In [27]:
T

Vector space morphism represented by the matrix:
[ 1  2  3]
[ 5 23  8]
[ 8  5  1]
Domain: Vector space of dimension 3 over Symbolic Ring
Codomain: Vector space of dimension 3 over Symbolic Ring

In [28]:
print(T)

Vector space morphism represented by the matrix:
[ 1  2  3]
[ 5 23  8]
[ 8  5  1]
Domain: Vector space of dimension 3 over Symbolic Ring
Codomain: Vector space of dimension 3 over Symbolic Ring


In [29]:
T.is_bijective()

True

#### Autovalores, auto vetores e diagonalização

In [30]:
d.charpoly()

x^3 + (-y^2 - 2*y)*x^2 + (2*y^3 + y^2)*x - y^4

In [31]:
a.eigenvalues()

[-1/2*(1/18*I*sqrt(24785605)*sqrt(3) + 27173/54)^(1/3)*(I*sqrt(3) + 1) - 353/9*(-I*sqrt(3) + 1)/(1/18*I*sqrt(24785605)*sqrt(3) + 27173/54)^(1/3) + 25/3,
 -1/2*(1/18*I*sqrt(24785605)*sqrt(3) + 27173/54)^(1/3)*(-I*sqrt(3) + 1) - 353/9*(I*sqrt(3) + 1)/(1/18*I*sqrt(24785605)*sqrt(3) + 27173/54)^(1/3) + 25/3,
 (1/18*I*sqrt(24785605)*sqrt(3) + 27173/54)^(1/3) + 706/9/(1/18*I*sqrt(24785605)*sqrt(3) + 27173/54)^(1/3) + 25/3]

In [32]:
a.eigenvectors_right()

[(-1/2*(1/18*I*sqrt(24785605)*sqrt(3) + 27173/54)^(1/3)*(I*sqrt(3) + 1) - 353/9*(-I*sqrt(3) + 1)/(1/18*I*sqrt(24785605)*sqrt(3) + 27173/54)^(1/3) + 25/3,
  [],
  1),
 (-1/2*(1/18*I*sqrt(24785605)*sqrt(3) + 27173/54)^(1/3)*(-I*sqrt(3) + 1) - 353/9*(I*sqrt(3) + 1)/(1/18*I*sqrt(24785605)*sqrt(3) + 27173/54)^(1/3) + 25/3,
  [],
  1),
 ((1/18*I*sqrt(24785605)*sqrt(3) + 27173/54)^(1/3) + 706/9/(1/18*I*sqrt(24785605)*sqrt(3) + 27173/54)^(1/3) + 25/3,
  [],
  1)]

In [33]:
k = matrix([[1,1,-3],[0,4,0],[-3,3,1]])

In [34]:
k.eigenvectors_right()

[(-2,
  [
  (1, 0, 1)
  ],
  1),
 (4,
  [
  (1, 0, -1)
  ],
  2)]

In [35]:
k.eigenmatrix_right()

(
[-2  0  0]  [ 1  1  0]
[ 0  4  0]  [ 0  0  0]
[ 0  0  4], [ 1 -1  0]
)

#### Exponencial de matrizes

$$e^A \equiv I+\sum_{n=1}^{\infty}\frac{A^n}{n!},$$
onde ${\displaystyle I\,}$ é a matriz identidade

In [36]:
m1 = matrix([[1,2],[2,2]]);m1

[1 2]
[2 2]

In [37]:
exp(m1)

[-1/34*((sqrt(17) - 17)*e^sqrt(17) - sqrt(17) - 17)*e^(-1/2*sqrt(17) + 3/2)              2/17*(sqrt(17)*e^sqrt(17) - sqrt(17))*e^(-1/2*sqrt(17) + 3/2)]
[             2/17*(sqrt(17)*e^sqrt(17) - sqrt(17))*e^(-1/2*sqrt(17) + 3/2)  1/34*((sqrt(17) + 17)*e^sqrt(17) - sqrt(17) + 17)*e^(-1/2*sqrt(17) + 3/2)]

#### Exercício

Dada a matriz de Pauli
$${\displaystyle \sigma _{2}={\begin{pmatrix}0&i\\-i&0\end{pmatrix}}.}$$

Calcule $e^{i\frac{\theta}{2}\sigma_2}$

In [38]:
var('theta')

theta

In [39]:
exp((i/2)*theta*matrix([[0,i],[-i,0]]))

[   1/2*(e^(I*theta) + 1)*e^(-1/2*I*theta)  1/2*(I*e^(I*theta) - I)*e^(-1/2*I*theta)]
[-1/2*(I*e^(I*theta) - I)*e^(-1/2*I*theta)    1/2*(e^(I*theta) + 1)*e^(-1/2*I*theta)]

In [40]:
x.simplify_rectform()

x

#### Geradores do grupo de Lorentz (Representação de spin 1 da algébra de Lie $\mathfrak{so}(1,3)$)

Rotações

In [41]:
J1 = I*matrix([[0,0,0,0],[0,0,0,0],[0,0,0,-1],[0,0,1,0]])
J2 = I*matrix([[0,0,0,0],[0,0,0,1],[0,0,0,0],[0,-1,0,0]])
J3 = I*matrix([[0,0,0,0],[0,0,-1,0],[0,1,0,0],[0,0,0,0]])

In [42]:
show(J1,J2,J3)

[ 0  0  0  0]
[ 0  0  0  0]
[ 0  0  0 -I]
[ 0  0  I  0] [ 0  0  0  0]
[ 0  0  0  I]
[ 0  0  0  0]
[ 0 -I  0  0] [ 0  0  0  0]
[ 0  0 -I  0]
[ 0  I  0  0]
[ 0  0  0  0]

In [43]:
th = var('theta',n=4);th

(theta0, theta1, theta2, theta3)

In [44]:
R1 = exp(I*th[1]*J1)

In [45]:
R2 = exp(I*th[2]*J2)

In [46]:
R3 = exp(I*th[3]*J3)

In [47]:
show(R1,R2,R3)

[                                        1                                         0                                         0                                         0]
[                                        0                                         1                                         0                                         0]
[                                        0                                         0    1/2*(e^(2*I*theta1) + 1)*e^(-I*theta1) -1/2*(I*e^(2*I*theta1) - I)*e^(-I*theta1)]
[                                        0                                         0  1/2*(I*e^(2*I*theta1) - I)*e^(-I*theta1)    1/2*(e^(2*I*theta1) + 1)*e^(-I*theta1)] [                                        1                                         0                                         0                                         0]
[                                        0    1/2*(e^(2*I*theta2) + 1)*e^(-I*theta2)                                         0  1/2*(I*e^(2*I*theta2) - I)*e^(-I*theta2)]
[                                        0                                         0                                         1                                         0]
[                                        0 -1/2*(I*e^(2*I*theta2) - I)*e^(-I*theta2)                                         0    1/2*(e^(2*I*theta2) + 1)*e^(-I*theta2)] [                                        1                                         0                                         0                                         0]
[                                        0    1/2*(e^(2*I*theta3) + 1)*e^(-I*theta3) -1/2*(I*e^(2*I*theta3) - I)*e^(-I*theta3)                                         0]
[                                        0  1/2*(I*e^(2*I*theta3) - I)*e^(-I*theta3)    1/2*(e^(2*I*theta3) + 1)*e^(-I*theta3)                                         0]
[                                        0                                         0                                         0                                         1]

In [48]:
R1[2,2].expand().simplify_rectform()

cos(theta1)

In [49]:
R1.expand()

[                                        1                                         0                                         0                                         0]
[                                        0                                         1                                         0                                         0]
[                                        0                                         0      1/2*e^(I*theta1) + 1/2*e^(-I*theta1) -1/2*I*e^(I*theta1) + 1/2*I*e^(-I*theta1)]
[                                        0                                         0  1/2*I*e^(I*theta1) - 1/2*I*e^(-I*theta1)      1/2*e^(I*theta1) + 1/2*e^(-I*theta1)]

Funçãozinha em Python

In [50]:
def resolve(M):
    for lin in range(4):
        for col in range(4):
            M[lin,col] = M[lin,col].expand().simplify_rectform()
    return M

In [51]:
resolve(R1);resolve(R2);resolve(R3)

[           1            0            0            0]
[           0  cos(theta3)  sin(theta3)            0]
[           0 -sin(theta3)  cos(theta3)            0]
[           0            0            0            1]

In [52]:
show(R1,R2,R3)

[           1            0            0            0]
[           0            1            0            0]
[           0            0  cos(theta1)  sin(theta1)]
[           0            0 -sin(theta1)  cos(theta1)] [           1            0            0            0]
[           0  cos(theta2)            0 -sin(theta2)]
[           0            0            1            0]
[           0  sin(theta2)            0  cos(theta2)] [           1            0            0            0]
[           0  cos(theta3)  sin(theta3)            0]
[           0 -sin(theta3)  cos(theta3)            0]
[           0            0            0            1]

Boosts

In [53]:
K1 = -I*matrix([[0,1,0,0],[1,0,0,0],[0,0,0,0],[0,0,0,0]])
K2 = -I*matrix([[0,0,1,0],[0,0,0,0],[1,0,0,0],[0,0,0,0]])
K3 = -I*matrix([[0,0,0,1],[0,0,0,0],[0,0,0,0],[1,0,0,0]])

In [54]:
show(K1,K2,K3)

[ 0 -I  0  0]
[-I  0  0  0]
[ 0  0  0  0]
[ 0  0  0  0] [ 0  0 -I  0]
[ 0  0  0  0]
[-I  0  0  0]
[ 0  0  0  0] [ 0  0  0 -I]
[ 0  0  0  0]
[ 0  0  0  0]
[-I  0  0  0]

In [55]:
B1 = exp(I*th[1]*K1).expand()
B2 = exp(I*th[1]*K2).expand()
B3 = exp(I*th[1]*K3).expand()

In [56]:
show(B1,B2,B3)

[ 1/2*e^(-theta1) + 1/2*e^theta1 -1/2*e^(-theta1) + 1/2*e^theta1                               0                               0]
[-1/2*e^(-theta1) + 1/2*e^theta1  1/2*e^(-theta1) + 1/2*e^theta1                               0                               0]
[                              0                               0                               1                               0]
[                              0                               0                               0                               1] [ 1/2*e^(-theta1) + 1/2*e^theta1                               0 -1/2*e^(-theta1) + 1/2*e^theta1                               0]
[                              0                               1                               0                               0]
[-1/2*e^(-theta1) + 1/2*e^theta1                               0  1/2*e^(-theta1) + 1/2*e^theta1                               0]
[                              0                               0                               0                               1] [ 1/2*e^(-theta1) + 1/2*e^theta1                               0                               0 -1/2*e^(-theta1) + 1/2*e^theta1]
[                              0                               1                               0                               0]
[                              0                               0                               1                               0]
[-1/2*e^(-theta1) + 1/2*e^theta1                               0                               0  1/2*e^(-theta1) + 1/2*e^theta1]

#### Verificando que $R_i$ e $B_i$ são transformações de Lorentz
$$\Lambda^T\eta\Lambda = \eta$$

In [57]:
eta = diagonal_matrix([-1,1,1,1]);eta

[-1  0  0  0]
[ 0  1  0  0]
[ 0  0  1  0]
[ 0  0  0  1]

In [58]:
(R1.transpose()*eta*R1).simplify_trig()

[-1  0  0  0]
[ 0  1  0  0]
[ 0  0  1  0]
[ 0  0  0  1]

In [59]:
(B3.transpose()*eta*B3).expand()

[-1  0  0  0]
[ 0  1  0  0]
[ 0  0  1  0]
[ 0  0  0  1]

#### Espaço de Minkowski

In [60]:
M = VectorSpace(SR,4, inner_product_matrix=eta)

In [61]:
w = M([3,2,1,2]);w

(3, 2, 1, 2)

In [62]:
u = M([3,0,1,2]);u

(3, 0, 1, 2)

In [63]:
w.dot_product(w) #Euclidiano

18

$$w^\mu u_\mu = \eta_{\mu\nu}w^\mu u^\nu = \eta(w,u)$$

In [64]:
w.inner_product(u) #Minkowski

-4

In [65]:
w*eta*u

-4

In [66]:
(w).inner_product(w)

0

In [67]:
(u).inner_product(u)

-4

In [68]:
w.norm()

3*sqrt(2)

In [69]:
sqrt(u*eta*u)

2*I